export const tile_types = {
    demolish: {
        color: null,
        id: -1,
        texture: null,
        unlocked: true,
        tile_data: {
            name: 'demolish',
            price: 0,
            maintainence: 0,
            tax: 0,
            population_max: 0,
            jobs: 0,
            power_provided: 0,
            power_taken: 0,
            water_provided: 0,
            water_taken: 0,
            requiresRoad: false,
            edited: true
        },
    },
    grass: {
        color: "#1d8038",
        id: 0,
        texture: null,
        unlocked: true,
        tile_data: {
            name: 'grass',
            price: 0,
            maintainence: 0,
            tax: 0,
            population_max: 0,
            jobs: 0,
            power_provided: 0,
            power_taken: 0,
            water_provided: 0,
            water_taken: 0,
            requiresRoad: false,
            edited: true
        },
    },
    road: {
        color: "#555",
        id: 1,
        texture: null,
        unlocked: true,
        tile_data: {
            name: 'road',
            price: 0,
            maintainence: 0,
            tax: 0,
            population_max: 0,
            jobs: 0,
            power_provided: 0,
            power_taken: 0,
            water_provided: 0,
            water_taken: 0,
            requiresRoad: false,
            edited: true
        },
    },
    house: {
        color: "yellow",
        id: 2,
        unlocked: true,
        tile_data: {
            name: 'house',
            price: 2,
            maintainence: 0,
            tax: 4,
            population_max: 4,
            jobs: 0,
            power_provided: 0,
            power_taken: 1,
            water_provided: 0,
            water_taken: 2,
            requiresRoad: true,
            edited: true
        },
    },
    shop: {
        color: "#3293a8",
        id: 3,
        unlocked: true,
        tile_data: {
            name: 'shop',
            price: 2,
            maintainence: 0,
            tax: 10,
            population_max: 0,
            jobs: 4,
            power_provided: 0,
            power_taken: 2,
            water_provided: 0,
            water_taken: 1,
            requiresRoad: true,
            edited: true
        },
    },
    water: {
        color: "blue",
        id: 4,
        unlocked: true,
        tile_data: {
            name: 'water',
            price: 0,
            maintainence: 0,
            tax: 0,
            population_max: 0,
            jobs: 0,
            power_provided: 0,
            power_taken: 0,
            water_provided: 0,
            water_taken: 0,
            requiresRoad: false,
            edited: true
        },
    },
    power: {
        color: "#727373",
        id: 5,
        unlocked: true,
        tile_data: {
            name: 'power',
            price: 5,
            maintainence: 4,
            tax: 4,
            population_max: 0,
            jobs: 3,
            power_provided: 10,
            power_taken: 0,
            water_provided: 0,
            water_taken: 5,
            requiresRoad: true,
            edited: true
        },
    },
    water_pump: {
        color: "#00008B",
        id: 6,
        unlocked: true,
        tile_data: {
            name: 'water_pump',
            price: 2,
            maintainence: 5,
            tax: 5,
            population_max: 0,
            jobs: 2,
            power_provided: 0,
            power_taken: 2,
            water_provided: 10,
            water_taken: 0,
            requiresRoad: true,
            edited: true
        },
    },
    house_med: {
        color: '#a88d32',
        id: 7,
        unlocked: false,
        tile_data: {
            name: 'house_med',
            price: 20,
            maintainence: 10,
            tax: 6,
            population_max: 10,
            jobs: 0,
            power_provided: 0,
            power_taken: 5,
            water_provided: 0,
            water_taken: 10,
            requiresRoad: true,
            edited: true
        },
    },
    shop_med: {
        color: '#5c32a8',
        id: 8,
        unlocked: false,
        tile_data: {
            name: 'shop_med',
            price: 25,
            maintainence: 15,
            tax: 10,
            population_max: 0,
            jobs: 10,
            power_provided: 0,
            power_taken: 10,
            water_provided: 0,
            water_taken: 10,
            requiresRoad: true,
            edited: true
        },
    },
    power_med: {
        color: 'grey',
        id: 9,
        unlocked: false,
        tile_data: {
            name: 'power_med',
            price: 30,
            maintainence: 15,
            tax: 10,
            population_max: 0,
            jobs: 10,
            power_provided: 50,
            power_taken: 0,
            water_provided: 0,
            water_taken: 10,
            requiresRoad: true,
            edited: true
        },
    },
    water_pump_med: {
        color: 'cyan',
        id: 10,
        unlocked: false,
        tile_data: {
            name: 'water_pump_med',
            price: 30,
            maintainence: 15,
            tax: 10,
            population_max: 0,
            jobs: 4,
            power_provided: 0,
            power_taken: 10,
            water_provided: 30,
            water_taken: 0,
            requiresRoad: true,
            edited: true
        },
    },
    house_high: {
        color: '#a86f32',
        id: 11,
        unlocked: false,
        tile_data: {
            name: 'house_high',
            price: 100,
            maintainence: 50,
            tax: 40,
            population_max: 100,
            jobs: 10,
            power_provided: 0,
            power_taken: 30,
            water_provided: 0,
            water_taken: 20,
            requiresRoad: true,
            edited: true
        },
    },
    shop_high: {
        color: '#6d32a8',
        id: 12,
        unlocked: false,
        tile_data: {
            name: 'shop_high',
            price: 120,
            maintainence: 50,
            tax: 60,
            population_max: 5,
            jobs: 40,
            power_provided: 0,
            power_taken: 30,
            water_provided: 0,
            water_taken: 20,
            requiresRoad: true,
            edited: true
        },
    },
    power_high: {
        color: 'black',
        id: 13,
        unlocked: false,
        tile_data: {
            name: 'power_high',
            price: 1000,
            maintainence: 100,
            tax: 100,
            population_max: 0,
            jobs: 50,
            power_provided: 500,
            power_taken: 0,
            water_provided: 0,
            water_taken: 500,
            requiresRoad: true,
            edited: true
        },
    },
    water_pump_high: {
        color: '#010154',
        id: 14,
        unlocked: false,
        tile_data: {
            name: 'water_pump_high',
            price: 500,
            maintainence: 150,
            tax: 110,
            population_max: 0,
            jobs: 25,
            power_provided: 0,
            power_taken: 50,
            water_provided: 1000,
            water_taken: 0,
            requiresRoad: true,
            edited: true
        },
    },
    police: {
        color: null,
        id: 15,
        unlocked: true,
        tile_data: {
            name: 'police',
            price: 4,
            maintainence: 3,
            tax: 10,
            population_max: 0,
            jobs: 5,
            power_provided: 0,
            power_taken: 1,
            water_provided: 0,
            water_taken: 4,
            requiresRoad: true,
            edited: true
        },
    },
    research_hall: {
        color: null,
        id: 16,
        unlocked: false,
        tile_data: {
            name: 'research_hall',
            price: 50,
            maintainence: 10,
            tax: 0,
            population_max: 0,
            jobs: 4,
            power_provided: 0,
            power_taken: 5,
            water_provided: 0,
            water_taken: 2,
            requiresRoad: true,
            edited: true
        },
    },
    border: {
        color: 'grey',
        id: 17,
        unlocked: true,
        tile_data: {
            name: 'border',
            price: 0,
            maintainence: 0,
            tax: 0,
            population_max: 0,
            jobs: 0,
            power_provided: 0,
            power_taken: 0,
            water_provided: 0,
            water_taken: 0,
            requiresRoad: false,
            edited: true
        },
    },
    office: {
        color: null,
        id: 18,
        unlocked: false,
        tile_data: {
            name: 'office',
            price: 10,
            maintainence: 3,
            tax: 8,
            population_max: 0,
            jobs: 5,
            power_provided: 0,
            power_taken: 3,
            water_provided: 0,
            water_taken: 3,
            requiresRoad: true,
            edited: true
        },
    },
    office_med: {
        color: null,
        id: 19,
        unlocked: false,
        tile_data: {
            name: 'office_med',
            price: 30,
            maintainence: 8,
            tax: 13,
            population_max: 0,
            jobs: 10,
            power_provided: 0,
            power_taken: 5,
            water_provided: 0,
            water_taken: 5,
            requiresRoad: true,
            edited: true
        },
    },
    office_high: {
        color: null,
        id: 20,
        unlocked: false,
        tile_data: {
            name: 'office_high',
            price: 100,
            maintainence: 10,
            tax: 20,
            population_max: 0,
            jobs: 20,
            power_provided: 0,
            power_taken: 10,
            water_provided: 0,
            water_taken: 10,
            requiresRoad: true,
            edited: true
        },
    },
    industrial: {
        color: null,
        id: 21,
        unlocked: true,
        tile_data: {
            name: 'industrial',
            price: 2,
            maintainence: 3,
            tax: 5,
            population_max: 0,
            jobs: 3,
            power_provided: 0,
            power_taken: 4,
            water_provided: 0,
            water_taken: 2,
            requiresRoad: true,
            edited: true
        },
    },
};
//# sourceMappingURL=tiles.js.map